//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordFlow.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordFlow.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_BackButton {
            get {
                return ResourceManager.GetString("FirstRunWizard_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_DownloadButton {
            get {
                return ResourceManager.GetString("FirstRunWizard_DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_DownloadComplete {
            get {
                return ResourceManager.GetString("FirstRunWizard_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载... 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_Downloading {
            get {
                return ResourceManager.GetString("FirstRunWizard_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要下载语音模型才能使用语音识别功能。
        ///
        ///模型大小约 238MB，请保持网络连接。 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_DownloadText {
            get {
                return ResourceManager.GetString("FirstRunWizard_DownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载模型 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_DownloadTitle {
            get {
                return ResourceManager.GetString("FirstRunWizard_DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🎤 智能语音输入
        ///按住说话，松手自动识别上屏 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_Feature1 {
            get {
                return ResourceManager.GetString("FirstRunWizard_Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🧠 本地 ASR 识别
        ///使用阿里达摩院 Paraformer 模型，离线可用 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_Feature2 {
            get {
                return ResourceManager.GetString("FirstRunWizard_Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📚 个人词库
        ///支持自定义词汇，AI 智能纠错 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_Feature3 {
            get {
                return ResourceManager.GetString("FirstRunWizard_Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📝 历史记录
        ///自动保存输入历史，方便查阅 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_Feature4 {
            get {
                return ResourceManager.GetString("FirstRunWizard_Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能介绍 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_FeaturesTitle {
            get {
                return ResourceManager.GetString("FirstRunWizard_FeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_FinishButton {
            get {
                return ResourceManager.GetString("FirstRunWizard_FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择您希望使用的界面语言： 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_LanguageText {
            get {
                return ResourceManager.GetString("FirstRunWizard_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择语言 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_LanguageTitle {
            get {
                return ResourceManager.GetString("FirstRunWizard_LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_NextButton {
            get {
                return ResourceManager.GetString("FirstRunWizard_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后下载 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_SkipButton {
            get {
                return ResourceManager.GetString("FirstRunWizard_SkipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 WordFlow 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_Title {
            get {
                return ResourceManager.GetString("FirstRunWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的智能语音输入助手 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_WelcomeSubtitle {
            get {
                return ResourceManager.GetString("FirstRunWizard_WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 WordFlow - 智能语音输入工具！
        ///
        ///本工具可以将您的语音实时转换为文字，并输入到任何应用程序中。
        ///
        ///点击&quot;下一步&quot;开始设置。 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_WelcomeText {
            get {
                return ResourceManager.GetString("FirstRunWizard_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🎉 欢迎使用 WordFlow！ 的本地化字符串。
        /// </summary>
        public static string FirstRunWizard_WelcomeTitle {
            get {
                return ResourceManager.GetString("FirstRunWizard_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🇺🇸 English 的本地化字符串。
        /// </summary>
        public static string Language_enUS {
            get {
                return ResourceManager.GetString("Language_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🇯🇵 日本語 的本地化字符串。
        /// </summary>
        public static string Language_jaJP {
            get {
                return ResourceManager.GetString("Language_jaJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🇰🇷 한국어 的本地化字符串。
        /// </summary>
        public static string Language_koKR {
            get {
                return ResourceManager.GetString("Language_koKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🇨🇳 简体中文 的本地化字符串。
        /// </summary>
        public static string Language_zhCN {
            get {
                return ResourceManager.GetString("Language_zhCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备就绪 的本地化字符串。
        /// </summary>
        public static string MainWindow_Ready {
            get {
                return ResourceManager.GetString("MainWindow_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按住 {0} 说话，松开后自动识别 的本地化字符串。
        /// </summary>
        public static string MainWindow_RecordHint {
            get {
                return ResourceManager.GetString("MainWindow_RecordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在录音... 的本地化字符串。
        /// </summary>
        public static string MainWindow_Recording {
            get {
                return ResourceManager.GetString("MainWindow_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WordFlow - 语音输入 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除吗？ 的本地化字符串。
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string Message_DownloadComplete {
            get {
                return ResourceManager.GetString("Message_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败，请检查网络连接 的本地化字符串。
        /// </summary>
        public static string Message_DownloadFailed {
            get {
                return ResourceManager.GetString("Message_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要重启应用才能生效，是否立即重启？ 的本地化字符串。
        /// </summary>
        public static string Message_RestartRequired {
            get {
                return ResourceManager.GetString("Message_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败，请重试 的本地化字符串。
        /// </summary>
        public static string Message_SaveFailed {
            get {
                return ResourceManager.GetString("Message_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置已保存 的本地化字符串。
        /// </summary>
        public static string Message_SaveSuccess {
            get {
                return ResourceManager.GetString("Message_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string ModelManager_Actions {
            get {
                return ResourceManager.GetString("ModelManager_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string ModelManager_CloseButton {
            get {
                return ResourceManager.GetString("ModelManager_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string ModelManager_Delete {
            get {
                return ResourceManager.GetString("ModelManager_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string ModelManager_Download {
            get {
                return ResourceManager.GetString("ModelManager_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        public static string ModelManager_Load {
            get {
                return ResourceManager.GetString("ModelManager_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型名称 的本地化字符串。
        /// </summary>
        public static string ModelManager_ModelName {
            get {
                return ResourceManager.GetString("ModelManager_ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型大小 的本地化字符串。
        /// </summary>
        public static string ModelManager_ModelSize {
            get {
                return ResourceManager.GetString("ModelManager_ModelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string ModelManager_ModelStatus {
            get {
                return ResourceManager.GetString("ModelManager_ModelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已安装 的本地化字符串。
        /// </summary>
        public static string ModelManager_Status_Installed {
            get {
                return ResourceManager.GetString("ModelManager_Status_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加载 的本地化字符串。
        /// </summary>
        public static string ModelManager_Status_Loaded {
            get {
                return ResourceManager.GetString("ModelManager_Status_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未下载 的本地化字符串。
        /// </summary>
        public static string ModelManager_Status_NotDownloaded {
            get {
                return ResourceManager.GetString("ModelManager_Status_NotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型管理 的本地化字符串。
        /// </summary>
        public static string ModelManager_Title {
            get {
                return ResourceManager.GetString("ModelManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_AboutTab {
            get {
                return ResourceManager.GetString("SettingsWindow_AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WordFlow - 智能语音输入工具 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_AppTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启动 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_AutoStart {
            get {
                return ResourceManager.GetString("SettingsWindow_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_CancelButton {
            get {
                return ResourceManager.GetString("SettingsWindow_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gitee 发布页面 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_GiteeLink {
            get {
                return ResourceManager.GetString("SettingsWindow_GiteeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub 项目地址 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_GitHubLink {
            get {
                return ResourceManager.GetString("SettingsWindow_GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按住选中的键说话，松开后自动识别 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_HotkeyHint {
            get {
                return ResourceManager.GetString("SettingsWindow_HotkeyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热键设置 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_HotkeysTab {
            get {
                return ResourceManager.GetString("SettingsWindow_HotkeysTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 💡 更改后需要重启应用生效 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_LanguageHint {
            get {
                return ResourceManager.GetString("SettingsWindow_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择界面语言： 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_LanguageLabel {
            get {
                return ResourceManager.GetString("SettingsWindow_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_LanguageTab {
            get {
                return ResourceManager.GetString("SettingsWindow_LanguageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📦 模型管理 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_ManageModel {
            get {
                return ResourceManager.GetString("SettingsWindow_ManageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载、切换或删除语音模型 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_ModelHint {
            get {
                return ResourceManager.GetString("SettingsWindow_ModelHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录音热键 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_RecordHotkeyGroup {
            get {
                return ResourceManager.GetString("SettingsWindow_RecordHotkeyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相关链接 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_RelatedLinks {
            get {
                return ResourceManager.GetString("SettingsWindow_RelatedLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🎯 重新运行首次向导 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_RunWizard {
            get {
                return ResourceManager.GetString("SettingsWindow_RunWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_SaveButton {
            get {
                return ResourceManager.GetString("SettingsWindow_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择录音触发键： 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_SelectHotkey {
            get {
                return ResourceManager.GetString("SettingsWindow_SelectHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时最小化到托盘 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_StartMinimized {
            get {
                return ResourceManager.GetString("SettingsWindow_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动设置 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_StartupGroup {
            get {
                return ResourceManager.GetString("SettingsWindow_StartupGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WordFlow 设置 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_ToolsTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_ToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本：2.0.0 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_Version {
            get {
                return ResourceManager.GetString("SettingsWindow_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看功能介绍和下载语音模型 的本地化字符串。
        /// </summary>
        public static string SettingsWindow_WizardHint {
            get {
                return ResourceManager.GetString("SettingsWindow_WizardHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史记录 的本地化字符串。
        /// </summary>
        public static string Tray_History {
            get {
                return ResourceManager.GetString("Tray_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示窗口 的本地化字符串。
        /// </summary>
        public static string Tray_ShowWindow {
            get {
                return ResourceManager.GetString("Tray_ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启 的本地化字符串。
        /// </summary>
        public static string Tray_StartOnBoot {
            get {
                return ResourceManager.GetString("Tray_StartOnBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词库管理 的本地化字符串。
        /// </summary>
        public static string Tray_VocabularyManager {
            get {
                return ResourceManager.GetString("Tray_VocabularyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加词汇 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_AddButton {
            get {
                return ResourceManager.GetString("VocabularyManager_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_CloseButton {
            get {
                return ResourceManager.GetString("VocabularyManager_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_DeleteButton {
            get {
                return ResourceManager.GetString("VocabularyManager_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_ExportButton {
            get {
                return ResourceManager.GetString("VocabularyManager_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用次数 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_Frequency {
            get {
                return ResourceManager.GetString("VocabularyManager_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_ImportButton {
            get {
                return ResourceManager.GetString("VocabularyManager_ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼音 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_Pinyin {
            get {
                return ResourceManager.GetString("VocabularyManager_Pinyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人词库管理 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_Title {
            get {
                return ResourceManager.GetString("VocabularyManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词汇 的本地化字符串。
        /// </summary>
        public static string VocabularyManager_Word {
            get {
                return ResourceManager.GetString("VocabularyManager_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        public static string Wizard_BackButton {
            get {
                return ResourceManager.GetString("Wizard_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算依据：普通人打字速度约 40 字/分钟，输入 300 字需 7.5 分钟；语音输入识别速度快，修正时间约 30 秒，综合节省约 7 分钟。 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_EfficiencyHint {
            get {
                return ResourceManager.GetString("Wizard_Card1_EfficiencyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每次输入 300 字，约节省 7 分钟 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_EfficiencyText {
            get {
                return ResourceManager.GetString("Wizard_Card1_EfficiencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⏱️ 效率提升 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_EfficiencyTitle {
            get {
                return ResourceManager.GetString("Wizard_Card1_EfficiencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击「下一步」了解更多功能 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_NextHint {
            get {
                return ResourceManager.GetString("Wizard_Card1_NextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速开始 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_QuickStartTitle {
            get {
                return ResourceManager.GetString("Wizard_Card1_QuickStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. 按住热键（` 键 或 右 Alt 键）说话 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_Step1 {
            get {
                return ResourceManager.GetString("Wizard_Card1_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. 松开热键，文字自动输入到当前光标位置 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_Step2 {
            get {
                return ResourceManager.GetString("Wizard_Card1_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3. 在设置中可修改热键和更多选项 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_Step3 {
            get {
                return ResourceManager.GetString("Wizard_Card1_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4. 在个人词库中管理专业词汇 的本地化字符串。
        /// </summary>
        public static string Wizard_Card1_Step4 {
            get {
                return ResourceManager.GetString("Wizard_Card1_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. 按住热键说话 的本地化字符串。
        /// </summary>
        public static string Wizard_Card2_Step1 {
            get {
                return ResourceManager.GetString("Wizard_Card2_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备选热键：右 Alt 键 的本地化字符串。
        /// </summary>
        public static string Wizard_Card2_Step1Alt {
            get {
                return ResourceManager.GetString("Wizard_Card2_Step1Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认热键：` 键（ESC 下方、数字 1 左侧） 的本地化字符串。
        /// </summary>
        public static string Wizard_Card2_Step1Detail {
            get {
                return ResourceManager.GetString("Wizard_Card2_Step1Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. 松开热键，语音自动转文字 的本地化字符串。
        /// </summary>
        public static string Wizard_Card2_Step2 {
            get {
                return ResourceManager.GetString("Wizard_Card2_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3. 文字直接输入到当前光标位置 的本地化字符串。
        /// </summary>
        public static string Wizard_Card2_Step3 {
            get {
                return ResourceManager.GetString("Wizard_Card2_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音输入方法 的本地化字符串。
        /// </summary>
        public static string Wizard_Card2_Title {
            get {
                return ResourceManager.GetString("Wizard_Card2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 录音热键：按住说话 的本地化字符串。
        /// </summary>
        public static string Wizard_Card3_Item1 {
            get {
                return ResourceManager.GetString("Wizard_Card3_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前默认：` 键 或 右 Alt 键 的本地化字符串。
        /// </summary>
        public static string Wizard_Card3_Item1Detail {
            get {
                return ResourceManager.GetString("Wizard_Card3_Item1Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 可在设置中自由切换热键 的本地化字符串。
        /// </summary>
        public static string Wizard_Card3_Item2 {
            get {
                return ResourceManager.GetString("Wizard_Card3_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 开机自启动，最小化到系统托盘 的本地化字符串。
        /// </summary>
        public static string Wizard_Card3_Item3 {
            get {
                return ResourceManager.GetString("Wizard_Card3_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 后台运行，不干扰正常工作 的本地化字符串。
        /// </summary>
        public static string Wizard_Card3_Item4 {
            get {
                return ResourceManager.GetString("Wizard_Card3_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热键设置 的本地化字符串。
        /// </summary>
        public static string Wizard_Card3_Title {
            get {
                return ResourceManager.GetString("Wizard_Card3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 右键点击系统托盘图标 的本地化字符串。
        /// </summary>
        public static string Wizard_Card4_Item1 {
            get {
                return ResourceManager.GetString("Wizard_Card4_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 选择「设置」进入设置界面 的本地化字符串。
        /// </summary>
        public static string Wizard_Card4_Item2 {
            get {
                return ResourceManager.GetString("Wizard_Card4_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 可修改热键、启动选项等 的本地化字符串。
        /// </summary>
        public static string Wizard_Card4_Item3 {
            get {
                return ResourceManager.GetString("Wizard_Card4_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 在「关于」页面可重新打开本向导 的本地化字符串。
        /// </summary>
        public static string Wizard_Card4_Item4 {
            get {
                return ResourceManager.GetString("Wizard_Card4_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置方法 的本地化字符串。
        /// </summary>
        public static string Wizard_Card4_Title {
            get {
                return ResourceManager.GetString("Wizard_Card4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 自动从您的修正记录中学习 的本地化字符串。
        /// </summary>
        public static string Wizard_Card5_Item1 {
            get {
                return ResourceManager.GetString("Wizard_Card5_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 支持导入导出专业词库 的本地化字符串。
        /// </summary>
        public static string Wizard_Card5_Item2 {
            get {
                return ResourceManager.GetString("Wizard_Card5_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 医疗、法律、编程等专业词汇优化 的本地化字符串。
        /// </summary>
        public static string Wizard_Card5_Item3 {
            get {
                return ResourceManager.GetString("Wizard_Card5_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 越用越懂你的表达习惯 的本地化字符串。
        /// </summary>
        public static string Wizard_Card5_Item4 {
            get {
                return ResourceManager.GetString("Wizard_Card5_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人词库训练 的本地化字符串。
        /// </summary>
        public static string Wizard_Card5_Title {
            get {
                return ResourceManager.GetString("Wizard_Card5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击「打开模型管理」按钮开始下载 的本地化字符串。
        /// </summary>
        public static string Wizard_Card6_ButtonHint {
            get {
                return ResourceManager.GetString("Wizard_Card6_ButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重要提示： 的本地化字符串。
        /// </summary>
        public static string Wizard_Card6_Important {
            get {
                return ResourceManager.GetString("Wizard_Card6_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 多语种模型：SenseVoice（支持中英日韩粤） 的本地化字符串。
        /// </summary>
        public static string Wizard_Card6_MultiLang {
            get {
                return ResourceManager.GetString("Wizard_Card6_MultiLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • 推荐模型：Paraformer 中文（约 200MB） 的本地化字符串。
        /// </summary>
        public static string Wizard_Card6_Recommend {
            get {
                return ResourceManager.GetString("Wizard_Card6_Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首次使用前，需要下载语音识别模型。 的本地化字符串。
        /// </summary>
        public static string Wizard_Card6_Text1 {
            get {
                return ResourceManager.GetString("Wizard_Card6_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载语音模型 的本地化字符串。
        /// </summary>
        public static string Wizard_Card6_Title {
            get {
                return ResourceManager.GetString("Wizard_Card6_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型已安装，开始使用语音输入吧！ 的本地化字符串。
        /// </summary>
        public static string Wizard_Complete_ModelStatus {
            get {
                return ResourceManager.GetString("Wizard_Complete_ModelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住快速开始 的本地化字符串。
        /// </summary>
        public static string Wizard_Complete_RememberTitle {
            get {
                return ResourceManager.GetString("Wizard_Complete_RememberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. 按住热键（` 键 或 右 Alt 键）说话 的本地化字符串。
        /// </summary>
        public static string Wizard_Complete_Step1 {
            get {
                return ResourceManager.GetString("Wizard_Complete_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. 松开热键，文字自动输入 的本地化字符串。
        /// </summary>
        public static string Wizard_Complete_Step2 {
            get {
                return ResourceManager.GetString("Wizard_Complete_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3. 在设置中可修改热键和更多选项 的本地化字符串。
        /// </summary>
        public static string Wizard_Complete_Step3 {
            get {
                return ResourceManager.GetString("Wizard_Complete_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4. 在个人词库中管理专业词汇 的本地化字符串。
        /// </summary>
        public static string Wizard_Complete_Step4 {
            get {
                return ResourceManager.GetString("Wizard_Complete_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置完成！ 的本地化字符串。
        /// </summary>
        public static string Wizard_Complete_Title {
            get {
                return ResourceManager.GetString("Wizard_Complete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始使用 的本地化字符串。
        /// </summary>
        public static string Wizard_FinishButton {
            get {
                return ResourceManager.GetString("Wizard_FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开模型管理 的本地化字符串。
        /// </summary>
        public static string Wizard_ModelManagerButton {
            get {
                return ResourceManager.GetString("Wizard_ModelManagerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string Wizard_NextButton {
            get {
                return ResourceManager.GetString("Wizard_NextButton", resourceCulture);
            }
        }
    }
}
