//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordFlow.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordFlow.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        #region Main Window
        public static string MainWindow_Title {
            get { return ResourceManager.GetString("MainWindow_Title", resourceCulture); }
        }
        
        public static string MainWindow_RecordHint {
            get { return ResourceManager.GetString("MainWindow_RecordHint", resourceCulture); }
        }
        
        public static string MainWindow_Recording {
            get { return ResourceManager.GetString("MainWindow_Recording", resourceCulture); }
        }
        
        public static string MainWindow_Ready {
            get { return ResourceManager.GetString("MainWindow_Ready", resourceCulture); }
        }
        
        public static string MW_OfflineASR {
            get { return ResourceManager.GetString("MW_OfflineASR", resourceCulture); }
        }
        
        public static string MW_ModelManager {
            get { return ResourceManager.GetString("MW_ModelManager", resourceCulture); }
        }
        
        public static string MW_ModelManager_Tooltip {
            get { return ResourceManager.GetString("MW_ModelManager_Tooltip", resourceCulture); }
        }
        
        public static string MW_PersonalDictionary {
            get { return ResourceManager.GetString("MW_PersonalDictionary", resourceCulture); }
        }
        
        public static string MW_PersonalDictionary_Tooltip {
            get { return ResourceManager.GetString("MW_PersonalDictionary_Tooltip", resourceCulture); }
        }
        
        public static string MW_ImportAudio {
            get { return ResourceManager.GetString("MW_ImportAudio", resourceCulture); }
        }
        
        public static string MW_ImportAudio_Tooltip {
            get { return ResourceManager.GetString("MW_ImportAudio_Tooltip", resourceCulture); }
        }
        
        public static string MW_Settings {
            get { return ResourceManager.GetString("MW_Settings", resourceCulture); }
        }
        
        public static string MW_Settings_Tooltip {
            get { return ResourceManager.GetString("MW_Settings_Tooltip", resourceCulture); }
        }
        
        public static string MW_Status_NotConnected {
            get { return ResourceManager.GetString("MW_Status_NotConnected", resourceCulture); }
        }
        
        public static string MW_Status_Ready {
            get { return ResourceManager.GetString("MW_Status_Ready", resourceCulture); }
        }
        
        public static string MW_StartRecording {
            get { return ResourceManager.GetString("MW_StartRecording", resourceCulture); }
        }
        
        public static string MW_RecordHint {
            get { return ResourceManager.GetString("MW_RecordHint", resourceCulture); }
        }
        
        public static string MW_HotkeyHint {
            get { return ResourceManager.GetString("MW_HotkeyHint", resourceCulture); }
        }
        
        public static string MW_PressToRecord {
            get { return ResourceManager.GetString("MW_PressToRecord", resourceCulture); }
        }
        
        public static string MW_PressToRecordWithKey {
            get { return ResourceManager.GetString("MW_PressToRecordWithKey", resourceCulture); }
        }
        
        public static string MW_HotkeyHintWithKey {
            get { return ResourceManager.GetString("MW_HotkeyHintWithKey", resourceCulture); }
        }
        
        public static string MW_HotkeyKeyDescription {
            get { return ResourceManager.GetString("MW_HotkeyKeyDescription", resourceCulture); }
        }
        
        public static string MW_Recording {
            get { return ResourceManager.GetString("MW_Recording", resourceCulture); }
        }
        
        public static string MW_TodayInput {
            get { return ResourceManager.GetString("MW_TodayInput", resourceCulture); }
        }
        
        public static string MW_TotalInput {
            get { return ResourceManager.GetString("MW_TotalInput", resourceCulture); }
        }
        
        public static string MW_SavedTime {
            get { return ResourceManager.GetString("MW_SavedTime", resourceCulture); }
        }
        
        public static string MW_Estimated {
            get { return ResourceManager.GetString("MW_Estimated", resourceCulture); }
        }
        
        public static string MW_Accuracy {
            get { return ResourceManager.GetString("MW_Accuracy", resourceCulture); }
        }
        
        public static string MW_BasedOnCorrections {
            get { return ResourceManager.GetString("MW_BasedOnCorrections", resourceCulture); }
        }
        
        public static string MW_NewbieGuide {
            get { return ResourceManager.GetString("MW_NewbieGuide", resourceCulture); }
        }
        
        public static string MW_HowToUseTitle {
            get { return ResourceManager.GetString("MW_HowToUseTitle", resourceCulture); }
        }
        
        public static string MW_HowToUse_Step1 {
            get { return ResourceManager.GetString("MW_HowToUse_Step1", resourceCulture); }
        }
        
        public static string MW_HowToUse_Step2 {
            get { return ResourceManager.GetString("MW_HowToUse_Step2", resourceCulture); }
        }
        
        public static string MW_HowToUse_Step3 {
            get { return ResourceManager.GetString("MW_HowToUse_Step3", resourceCulture); }
        }
        
        public static string MW_HowToUse_Step4 {
            get { return ResourceManager.GetString("MW_HowToUse_Step4", resourceCulture); }
        }
        
        public static string MW_TipsTitle {
            get { return ResourceManager.GetString("MW_TipsTitle", resourceCulture); }
        }
        
        public static string MW_Tip1 {
            get { return ResourceManager.GetString("MW_Tip1", resourceCulture); }
        }
        
        public static string MW_Tip2 {
            get { return ResourceManager.GetString("MW_Tip2", resourceCulture); }
        }
        
        public static string MW_Tip3 {
            get { return ResourceManager.GetString("MW_Tip3", resourceCulture); }
        }
        
        public static string MW_Tip4 {
            get { return ResourceManager.GetString("MW_Tip4", resourceCulture); }
        }
        
        public static string MW_InputExplanationTitle {
            get { return ResourceManager.GetString("MW_InputExplanationTitle", resourceCulture); }
        }
        
        public static string MW_InputExplanationText {
            get { return ResourceManager.GetString("MW_InputExplanationText", resourceCulture); }
        }
        
        public static string MW_HistoryHint {
            get { return ResourceManager.GetString("MW_HistoryHint", resourceCulture); }
        }
        
        public static string MW_Characters {
            get { return ResourceManager.GetString("MW_Characters", resourceCulture); }
        }
        #endregion
        
        #region Settings Window
        public static string SettingsWindow_Title {
            get { return ResourceManager.GetString("SettingsWindow_Title", resourceCulture); }
        }
        
        public static string SettingsWindow_HotkeysTab {
            get { return ResourceManager.GetString("SettingsWindow_HotkeysTab", resourceCulture); }
        }
        
        public static string SettingsWindow_LanguageTab {
            get { return ResourceManager.GetString("SettingsWindow_LanguageTab", resourceCulture); }
        }
        
        public static string SettingsWindow_AboutTab {
            get { return ResourceManager.GetString("SettingsWindow_AboutTab", resourceCulture); }
        }
        
        public static string SettingsWindow_RecordHotkeyGroup {
            get { return ResourceManager.GetString("SettingsWindow_RecordHotkeyGroup", resourceCulture); }
        }
        
        public static string SettingsWindow_SelectHotkey {
            get { return ResourceManager.GetString("SettingsWindow_SelectHotkey", resourceCulture); }
        }
        
        public static string SettingsWindow_HotkeyHint {
            get { return ResourceManager.GetString("SettingsWindow_HotkeyHint", resourceCulture); }
        }
        
        public static string SettingsWindow_StartupGroup {
            get { return ResourceManager.GetString("SettingsWindow_StartupGroup", resourceCulture); }
        }
        
        public static string SettingsWindow_AutoStart {
            get { return ResourceManager.GetString("SettingsWindow_AutoStart", resourceCulture); }
        }
        
        public static string SettingsWindow_StartMinimized {
            get { return ResourceManager.GetString("SettingsWindow_StartMinimized", resourceCulture); }
        }
        
        public static string SettingsWindow_LanguageLabel {
            get { return ResourceManager.GetString("SettingsWindow_LanguageLabel", resourceCulture); }
        }
        
        public static string SettingsWindow_LanguageHint {
            get { return ResourceManager.GetString("SettingsWindow_LanguageHint", resourceCulture); }
        }
        
        public static string SettingsWindow_SaveButton {
            get { return ResourceManager.GetString("SettingsWindow_SaveButton", resourceCulture); }
        }
        
        public static string SettingsWindow_CancelButton {
            get { return ResourceManager.GetString("SettingsWindow_CancelButton", resourceCulture); }
        }
        
        public static string SettingsWindow_AppTitle {
            get { return ResourceManager.GetString("SettingsWindow_AppTitle", resourceCulture); }
        }
        
        public static string SettingsWindow_Version {
            get { return ResourceManager.GetString("SettingsWindow_Version", resourceCulture); }
        }
        
        public static string SettingsWindow_RelatedLinks {
            get { return ResourceManager.GetString("SettingsWindow_RelatedLinks", resourceCulture); }
        }
        
        public static string SettingsWindow_GitHubLink {
            get { return ResourceManager.GetString("SettingsWindow_GitHubLink", resourceCulture); }
        }
        
        public static string SettingsWindow_GiteeLink {
            get { return ResourceManager.GetString("SettingsWindow_GiteeLink", resourceCulture); }
        }
        
        public static string SettingsWindow_ToolsTitle {
            get { return ResourceManager.GetString("SettingsWindow_ToolsTitle", resourceCulture); }
        }
        
        public static string SettingsWindow_RunWizard {
            get { return ResourceManager.GetString("SettingsWindow_RunWizard", resourceCulture); }
        }
        
        public static string SettingsWindow_WizardHint {
            get { return ResourceManager.GetString("SettingsWindow_WizardHint", resourceCulture); }
        }
        
        public static string SettingsWindow_ManageModel {
            get { return ResourceManager.GetString("SettingsWindow_ManageModel", resourceCulture); }
        }
        
        public static string SettingsWindow_ModelHint {
            get { return ResourceManager.GetString("SettingsWindow_ModelHint", resourceCulture); }
        }
        
        public static string SettingsWindow_CheckUpdate {
            get { return ResourceManager.GetString("SettingsWindow_CheckUpdate", resourceCulture); }
        }
        
        public static string SettingsWindow_CheckUpdateHint {
            get { return ResourceManager.GetString("SettingsWindow_CheckUpdateHint", resourceCulture); }
        }
        
        public static string SettingsWindow_CheckingUpdate {
            get { return ResourceManager.GetString("SettingsWindow_CheckingUpdate", resourceCulture); }
        }
        
        public static string SettingsWindow_VersionLabel {
            get { return ResourceManager.GetString("SettingsWindow_VersionLabel", resourceCulture); }
        }
        
        public static string SettingsWindow_WizardButton {
            get { return ResourceManager.GetString("SettingsWindow_WizardButton", resourceCulture); }
        }
        
        public static string SettingsWindow_ManageModelButton {
            get { return ResourceManager.GetString("SettingsWindow_ManageModelButton", resourceCulture); }
        }
        
        public static string SettingsWindow_Save {
            get { return ResourceManager.GetString("SettingsWindow_Save", resourceCulture); }
        }
        
        public static string SettingsWindow_Cancel {
            get { return ResourceManager.GetString("SettingsWindow_Cancel", resourceCulture); }
        }
        #endregion
        
        #region Language Options
        public static string Language_zhCN {
            get { return ResourceManager.GetString("Language_zhCN", resourceCulture); }
        }
        
        public static string Language_enUS {
            get { return ResourceManager.GetString("Language_enUS", resourceCulture); }
        }
        
        public static string Language_jaJP {
            get { return ResourceManager.GetString("Language_jaJP", resourceCulture); }
        }
        
        public static string Language_koKR {
            get { return ResourceManager.GetString("Language_koKR", resourceCulture); }
        }
        #endregion
        
        #region First Run Wizard
        public static string FirstRunWizard_Title {
            get { return ResourceManager.GetString("FirstRunWizard_Title", resourceCulture); }
        }
        
        public static string FirstRunWizard_WelcomeTitle {
            get { return ResourceManager.GetString("FirstRunWizard_WelcomeTitle", resourceCulture); }
        }
        
        public static string FirstRunWizard_WelcomeSubtitle {
            get { return ResourceManager.GetString("FirstRunWizard_WelcomeSubtitle", resourceCulture); }
        }
        
        public static string FirstRunWizard_WelcomeText {
            get { return ResourceManager.GetString("FirstRunWizard_WelcomeText", resourceCulture); }
        }
        
        public static string FirstRunWizard_LanguageTitle {
            get { return ResourceManager.GetString("FirstRunWizard_LanguageTitle", resourceCulture); }
        }
        
        public static string FirstRunWizard_LanguageText {
            get { return ResourceManager.GetString("FirstRunWizard_LanguageText", resourceCulture); }
        }
        
        public static string FirstRunWizard_FeaturesTitle {
            get { return ResourceManager.GetString("FirstRunWizard_FeaturesTitle", resourceCulture); }
        }
        
        public static string FirstRunWizard_Feature1 {
            get { return ResourceManager.GetString("FirstRunWizard_Feature1", resourceCulture); }
        }
        
        public static string FirstRunWizard_Feature2 {
            get { return ResourceManager.GetString("FirstRunWizard_Feature2", resourceCulture); }
        }
        
        public static string FirstRunWizard_Feature3 {
            get { return ResourceManager.GetString("FirstRunWizard_Feature3", resourceCulture); }
        }
        
        public static string FirstRunWizard_Feature4 {
            get { return ResourceManager.GetString("FirstRunWizard_Feature4", resourceCulture); }
        }
        
        public static string FirstRunWizard_DownloadTitle {
            get { return ResourceManager.GetString("FirstRunWizard_DownloadTitle", resourceCulture); }
        }
        
        public static string FirstRunWizard_DownloadText {
            get { return ResourceManager.GetString("FirstRunWizard_DownloadText", resourceCulture); }
        }
        
        public static string FirstRunWizard_DownloadButton {
            get { return ResourceManager.GetString("FirstRunWizard_DownloadButton", resourceCulture); }
        }
        
        public static string FirstRunWizard_Downloading {
            get { return ResourceManager.GetString("FirstRunWizard_Downloading", resourceCulture); }
        }
        
        public static string FirstRunWizard_DownloadComplete {
            get { return ResourceManager.GetString("FirstRunWizard_DownloadComplete", resourceCulture); }
        }
        
        public static string FirstRunWizard_NextButton {
            get { return ResourceManager.GetString("FirstRunWizard_NextButton", resourceCulture); }
        }
        
        public static string FirstRunWizard_BackButton {
            get { return ResourceManager.GetString("FirstRunWizard_BackButton", resourceCulture); }
        }
        
        public static string FirstRunWizard_FinishButton {
            get { return ResourceManager.GetString("FirstRunWizard_FinishButton", resourceCulture); }
        }
        
        public static string FirstRunWizard_SkipButton {
            get { return ResourceManager.GetString("FirstRunWizard_SkipButton", resourceCulture); }
        }
        
        // Card 1
        public static string Wizard_Card1_EfficiencyTitle {
            get { return ResourceManager.GetString("Wizard_Card1_EfficiencyTitle", resourceCulture); }
        }
        
        public static string Wizard_Card1_EfficiencyText {
            get { return ResourceManager.GetString("Wizard_Card1_EfficiencyText", resourceCulture); }
        }
        
        public static string Wizard_Card1_EfficiencyHint {
            get { return ResourceManager.GetString("Wizard_Card1_EfficiencyHint", resourceCulture); }
        }
        
        public static string Wizard_Card1_QuickStartTitle {
            get { return ResourceManager.GetString("Wizard_Card1_QuickStartTitle", resourceCulture); }
        }
        
        public static string Wizard_Card1_Step1 {
            get { return ResourceManager.GetString("Wizard_Card1_Step1", resourceCulture); }
        }
        
        public static string Wizard_Card1_Step2 {
            get { return ResourceManager.GetString("Wizard_Card1_Step2", resourceCulture); }
        }
        
        public static string Wizard_Card1_Step3 {
            get { return ResourceManager.GetString("Wizard_Card1_Step3", resourceCulture); }
        }
        
        public static string Wizard_Card1_Step4 {
            get { return ResourceManager.GetString("Wizard_Card1_Step4", resourceCulture); }
        }
        
        public static string Wizard_Card1_NextHint {
            get { return ResourceManager.GetString("Wizard_Card1_NextHint", resourceCulture); }
        }
        
        // Card 2
        public static string Wizard_Card2_Title {
            get { return ResourceManager.GetString("Wizard_Card2_Title", resourceCulture); }
        }
        
        public static string Wizard_Card2_Step1 {
            get { return ResourceManager.GetString("Wizard_Card2_Step1", resourceCulture); }
        }
        
        public static string Wizard_Card2_Step1Detail {
            get { return ResourceManager.GetString("Wizard_Card2_Step1Detail", resourceCulture); }
        }
        
        public static string Wizard_Card2_Step1Alt {
            get { return ResourceManager.GetString("Wizard_Card2_Step1Alt", resourceCulture); }
        }
        
        public static string Wizard_Card2_Step2 {
            get { return ResourceManager.GetString("Wizard_Card2_Step2", resourceCulture); }
        }
        
        public static string Wizard_Card2_Step3 {
            get { return ResourceManager.GetString("Wizard_Card2_Step3", resourceCulture); }
        }
        
        // Card 3
        public static string Wizard_Card3_Title {
            get { return ResourceManager.GetString("Wizard_Card3_Title", resourceCulture); }
        }
        
        public static string Wizard_Card3_Item1 {
            get { return ResourceManager.GetString("Wizard_Card3_Item1", resourceCulture); }
        }
        
        public static string Wizard_Card3_Item1Detail {
            get { return ResourceManager.GetString("Wizard_Card3_Item1Detail", resourceCulture); }
        }
        
        public static string Wizard_Card3_Item2 {
            get { return ResourceManager.GetString("Wizard_Card3_Item2", resourceCulture); }
        }
        
        public static string Wizard_Card3_Item3 {
            get { return ResourceManager.GetString("Wizard_Card3_Item3", resourceCulture); }
        }
        
        public static string Wizard_Card3_Item4 {
            get { return ResourceManager.GetString("Wizard_Card3_Item4", resourceCulture); }
        }
        
        // Card 4
        public static string Wizard_Card4_Title {
            get { return ResourceManager.GetString("Wizard_Card4_Title", resourceCulture); }
        }
        
        public static string Wizard_Card4_Item1 {
            get { return ResourceManager.GetString("Wizard_Card4_Item1", resourceCulture); }
        }
        
        public static string Wizard_Card4_Item2 {
            get { return ResourceManager.GetString("Wizard_Card4_Item2", resourceCulture); }
        }
        
        public static string Wizard_Card4_Item3 {
            get { return ResourceManager.GetString("Wizard_Card4_Item3", resourceCulture); }
        }
        
        public static string Wizard_Card4_Item4 {
            get { return ResourceManager.GetString("Wizard_Card4_Item4", resourceCulture); }
        }
        
        // Card 5
        public static string Wizard_Card5_Title {
            get { return ResourceManager.GetString("Wizard_Card5_Title", resourceCulture); }
        }
        
        public static string Wizard_Card5_Item1 {
            get { return ResourceManager.GetString("Wizard_Card5_Item1", resourceCulture); }
        }
        
        public static string Wizard_Card5_Item2 {
            get { return ResourceManager.GetString("Wizard_Card5_Item2", resourceCulture); }
        }
        
        public static string Wizard_Card5_Item3 {
            get { return ResourceManager.GetString("Wizard_Card5_Item3", resourceCulture); }
        }
        
        public static string Wizard_Card5_Item4 {
            get { return ResourceManager.GetString("Wizard_Card5_Item4", resourceCulture); }
        }
        
        // Card 6
        public static string Wizard_Card6_Title {
            get { return ResourceManager.GetString("Wizard_Card6_Title", resourceCulture); }
        }
        
        public static string Wizard_Card6_Important {
            get { return ResourceManager.GetString("Wizard_Card6_Important", resourceCulture); }
        }
        
        public static string Wizard_Card6_Text1 {
            get { return ResourceManager.GetString("Wizard_Card6_Text1", resourceCulture); }
        }
        
        public static string Wizard_Card6_Recommend {
            get { return ResourceManager.GetString("Wizard_Card6_Recommend", resourceCulture); }
        }
        
        public static string Wizard_Card6_MultiLang {
            get { return ResourceManager.GetString("Wizard_Card6_MultiLang", resourceCulture); }
        }
        
        public static string Wizard_Card6_ButtonHint {
            get { return ResourceManager.GetString("Wizard_Card6_ButtonHint", resourceCulture); }
        }
        
        public static string Wizard_Card6_LanguagesList {
            get { return ResourceManager.GetString("Wizard_Card6_LanguagesList", resourceCulture); }
        }
        
        // Complete Page
        public static string Wizard_Complete_Title {
            get { return ResourceManager.GetString("Wizard_Complete_Title", resourceCulture); }
        }
        
        public static string Wizard_Complete_ModelStatus {
            get { return ResourceManager.GetString("Wizard_Complete_ModelStatus", resourceCulture); }
        }
        
        public static string Wizard_Complete_RememberTitle {
            get { return ResourceManager.GetString("Wizard_Complete_RememberTitle", resourceCulture); }
        }
        
        public static string Wizard_Complete_Step1 {
            get { return ResourceManager.GetString("Wizard_Complete_Step1", resourceCulture); }
        }
        
        public static string Wizard_Complete_Step2 {
            get { return ResourceManager.GetString("Wizard_Complete_Step2", resourceCulture); }
        }
        
        public static string Wizard_Complete_Step3 {
            get { return ResourceManager.GetString("Wizard_Complete_Step3", resourceCulture); }
        }
        
        public static string Wizard_Complete_Step4 {
            get { return ResourceManager.GetString("Wizard_Complete_Step4", resourceCulture); }
        }
        
        // Buttons
        public static string Wizard_BackButton {
            get { return ResourceManager.GetString("Wizard_BackButton", resourceCulture); }
        }
        
        public static string Wizard_NextButton {
            get { return ResourceManager.GetString("Wizard_NextButton", resourceCulture); }
        }
        
        public static string Wizard_FinishButton {
            get { return ResourceManager.GetString("Wizard_FinishButton", resourceCulture); }
        }
        
        public static string Wizard_ModelManagerButton {
            get { return ResourceManager.GetString("Wizard_ModelManagerButton", resourceCulture); }
        }
        
        // Background Download
        public static string Wizard_BackgroundDownload {
            get { return ResourceManager.GetString("Wizard_BackgroundDownload", resourceCulture); }
        }
        
        public static string Wizard_Downloading {
            get { return ResourceManager.GetString("Wizard_Downloading", resourceCulture); }
        }
        
        public static string Wizard_DownloadComplete {
            get { return ResourceManager.GetString("Wizard_DownloadComplete", resourceCulture); }
        }
        
        public static string Wizard_DownloadFailed {
            get { return ResourceManager.GetString("Wizard_DownloadFailed", resourceCulture); }
        }
        
        public static string Wizard_DownloadCancelled {
            get { return ResourceManager.GetString("Wizard_DownloadCancelled", resourceCulture); }
        }
        
        public static string Wizard_ProgressHint {
            get { return ResourceManager.GetString("Wizard_ProgressHint", resourceCulture); }
        }
        
        public static string Wizard_ClickNextToContinue {
            get { return ResourceManager.GetString("Wizard_ClickNextToContinue", resourceCulture); }
        }
        
        public static string Wizard_WaitDownloadComplete {
            get { return ResourceManager.GetString("Wizard_WaitDownloadComplete", resourceCulture); }
        }
        
        public static string Wizard_DownloadProgress {
            get { return ResourceManager.GetString("Wizard_DownloadProgress", resourceCulture); }
        }
        
        public static string Wizard_ModelDownloading {
            get { return ResourceManager.GetString("Wizard_ModelDownloading", resourceCulture); }
        }
        
        public static string Wizard_ModelDownloaded {
            get { return ResourceManager.GetString("Wizard_ModelDownloaded", resourceCulture); }
        }
        
        public static string Wizard_StartDownload {
            get { return ResourceManager.GetString("Wizard_StartDownload", resourceCulture); }
        }
        
        public static string Wizard_CancelDownload {
            get { return ResourceManager.GetString("Wizard_CancelDownload", resourceCulture); }
        }
        
        public static string Wizard_OpenModelManager {
            get { return ResourceManager.GetString("Wizard_OpenModelManager", resourceCulture); }
        }
        
        public static string Wizard_WarningTitle {
            get { return ResourceManager.GetString("Wizard_WarningTitle", resourceCulture); }
        }
        
        public static string Wizard_NoModelWarning {
            get { return ResourceManager.GetString("Wizard_NoModelWarning", resourceCulture); }
        }
        
        public static string Wizard_Complete_ModelStatus_Installed {
            get { return ResourceManager.GetString("Wizard_Complete_ModelStatus_Installed", resourceCulture); }
        }
        
        public static string Wizard_Complete_ModelStatus_NotInstalled {
            get { return ResourceManager.GetString("Wizard_Complete_ModelStatus_NotInstalled", resourceCulture); }
        }
        
        public static string Wizard_StartButton {
            get { return ResourceManager.GetString("Wizard_StartButton", resourceCulture); }
        }
        
        public static string Wizard_StartDownloadButton {
            get { return ResourceManager.GetString("Wizard_StartDownloadButton", resourceCulture); }
        }
        
        public static string Wizard_CancelDownloadButton {
            get { return ResourceManager.GetString("Wizard_CancelDownloadButton", resourceCulture); }
        }
        
        public static string Wizard_ProgressNetworkHint {
            get { return ResourceManager.GetString("Wizard_ProgressNetworkHint", resourceCulture); }
        }
        
        public static string Wizard_DownloadCompleteHint {
            get { return ResourceManager.GetString("Wizard_DownloadCompleteHint", resourceCulture); }
        }
        #endregion
        
        #region Model Manager
        public static string ModelManager_Title {
            get { return ResourceManager.GetString("ModelManager_Title", resourceCulture); }
        }
        
        public static string ModelManager_Subtitle {
            get { return ResourceManager.GetString("ModelManager_Subtitle", resourceCulture); }
        }
        
        public static string ModelManager_ModelName {
            get { return ResourceManager.GetString("ModelManager_ModelName", resourceCulture); }
        }
        
        public static string ModelManager_ModelSize {
            get { return ResourceManager.GetString("ModelManager_ModelSize", resourceCulture); }
        }
        
        public static string ModelManager_ModelStatus {
            get { return ResourceManager.GetString("ModelManager_ModelStatus", resourceCulture); }
        }
        
        public static string ModelManager_Actions {
            get { return ResourceManager.GetString("ModelManager_Actions", resourceCulture); }
        }
        
        public static string ModelManager_Download {
            get { return ResourceManager.GetString("ModelManager_Download", resourceCulture); }
        }
        
        public static string ModelManager_Delete {
            get { return ResourceManager.GetString("ModelManager_Delete", resourceCulture); }
        }
        
        public static string ModelManager_Load {
            get { return ResourceManager.GetString("ModelManager_Load", resourceCulture); }
        }
        
        public static string ModelManager_Status_Installed {
            get { return ResourceManager.GetString("ModelManager_Status_Installed", resourceCulture); }
        }
        
        public static string ModelManager_Status_NotDownloaded {
            get { return ResourceManager.GetString("ModelManager_Status_NotDownloaded", resourceCulture); }
        }
        
        public static string ModelManager_Status_Loaded {
            get { return ResourceManager.GetString("ModelManager_Status_Loaded", resourceCulture); }
        }
        
        public static string ModelManager_CloseButton {
            get { return ResourceManager.GetString("ModelManager_CloseButton", resourceCulture); }
        }
        
        public static string ModelManager_RefreshButton {
            get { return ResourceManager.GetString("ModelManager_RefreshButton", resourceCulture); }
        }
        
        public static string ModelManager_BackgroundDownloadButton {
            get { return ResourceManager.GetString("ModelManager_BackgroundDownloadButton", resourceCulture); }
        }
        
        public static string ModelManager_CloseButton2 {
            get { return ResourceManager.GetString("ModelManager_CloseButton2", resourceCulture); }
        }
        
        public static string ModelManager_DownloadProgress {
            get { return ResourceManager.GetString("ModelManager_DownloadProgress", resourceCulture); }
        }
        
        public static string ModelManager_NoModelsAvailable {
            get { return ResourceManager.GetString("ModelManager_NoModelsAvailable", resourceCulture); }
        }
        
        public static string ModelManager_Status_NotDownloaded_Short {
            get { return ResourceManager.GetString("ModelManager_Status_NotDownloaded_Short", resourceCulture); }
        }
        
        public static string ModelManager_Status_Current {
            get { return ResourceManager.GetString("ModelManager_Status_Current", resourceCulture); }
        }
        
        public static string ModelManager_Status_Installed_Short {
            get { return ResourceManager.GetString("ModelManager_Status_Installed_Short", resourceCulture); }
        }
        
        public static string ModelManager_Button_Use {
            get { return ResourceManager.GetString("ModelManager_Button_Use", resourceCulture); }
        }
        
        public static string ModelManager_Button_Delete {
            get { return ResourceManager.GetString("ModelManager_Button_Delete", resourceCulture); }
        }
        
        public static string ModelManager_Button_Download {
            get { return ResourceManager.GetString("ModelManager_Button_Download", resourceCulture); }
        }
        
        public static string ModelManager_Button_CancelDownload {
            get { return ResourceManager.GetString("ModelManager_Button_CancelDownload", resourceCulture); }
        }
        
        public static string ModelManager_DownloadComplete {
            get { return ResourceManager.GetString("ModelManager_DownloadComplete", resourceCulture); }
        }
        
        public static string ModelManager_DownloadFailed {
            get { return ResourceManager.GetString("ModelManager_DownloadFailed", resourceCulture); }
        }
        
        public static string ModelManager_DownloadCancelled {
            get { return ResourceManager.GetString("ModelManager_DownloadCancelled", resourceCulture); }
        }
        
        public static string ModelManager_ConfirmDownload {
            get { return ResourceManager.GetString("ModelManager_ConfirmDownload", resourceCulture); }
        }
        
        public static string ModelManager_ConfirmDelete {
            get { return ResourceManager.GetString("ModelManager_ConfirmDelete", resourceCulture); }
        }
        
        public static string ModelManager_ServiceNotRunning {
            get { return ResourceManager.GetString("ModelManager_ServiceNotRunning", resourceCulture); }
        }
        
        public static string ModelManager_SwitchSuccess {
            get { return ResourceManager.GetString("ModelManager_SwitchSuccess", resourceCulture); }
        }
        
        public static string ModelManager_SwitchFailed {
            get { return ResourceManager.GetString("ModelManager_SwitchFailed", resourceCulture); }
        }
        
        public static string ModelManager_LoadSuccess {
            get { return ResourceManager.GetString("ModelManager_LoadSuccess", resourceCulture); }
        }
        
        public static string ModelManager_ServiceStartPrompt {
            get { return ResourceManager.GetString("ModelManager_ServiceStartPrompt", resourceCulture); }
        }
        
        public static string ModelManager_ServiceStartSuccess {
            get { return ResourceManager.GetString("ModelManager_ServiceStartSuccess", resourceCulture); }
        }
        
        public static string ModelManager_ServiceStartFailed {
            get { return ResourceManager.GetString("ModelManager_ServiceStartFailed", resourceCulture); }
        }
        
        public static string ModelManager_CloseWhileDownloading {
            get { return ResourceManager.GetString("ModelManager_CloseWhileDownloading", resourceCulture); }
        }
        
        public static string ModelManager_DownloadingPrompt {
            get { return ResourceManager.GetString("ModelManager_DownloadingPrompt", resourceCulture); }
        }
        
        public static string ModelManager_ModelNotFound {
            get { return ResourceManager.GetString("ModelManager_ModelNotFound", resourceCulture); }
        }
        
        public static string ModelManager_LocalModel {
            get { return ResourceManager.GetString("ModelManager_LocalModel", resourceCulture); }
        }
        
        // Model Descriptions
        public static string Model_SenseVoice_Name {
            get { return ResourceManager.GetString("Model_SenseVoice_Name", resourceCulture); }
        }
        
        public static string Model_SenseVoice_Description {
            get { return ResourceManager.GetString("Model_SenseVoice_Description", resourceCulture); }
        }
        
        public static string Model_SenseVoice_Languages {
            get { return ResourceManager.GetString("Model_SenseVoice_Languages", resourceCulture); }
        }
        
        public static string Model_SenseVoice_Size {
            get { return ResourceManager.GetString("Model_SenseVoice_Size", resourceCulture); }
        }
        
        public static string Model_SenseVoice_Features {
            get { return ResourceManager.GetString("Model_SenseVoice_Features", resourceCulture); }
        }
        #endregion
        
        #region Vocabulary Manager
        public static string VocabularyManager_Title {
            get { return ResourceManager.GetString("VocabularyManager_Title", resourceCulture); }
        }
        
        public static string VocabularyManager_AddButton {
            get { return ResourceManager.GetString("VocabularyManager_AddButton", resourceCulture); }
        }
        
        public static string VocabularyManager_DeleteButton {
            get { return ResourceManager.GetString("VocabularyManager_DeleteButton", resourceCulture); }
        }
        
        public static string VocabularyManager_ExportButton {
            get { return ResourceManager.GetString("VocabularyManager_ExportButton", resourceCulture); }
        }
        
        public static string VocabularyManager_ImportButton {
            get { return ResourceManager.GetString("VocabularyManager_ImportButton", resourceCulture); }
        }
        
        public static string VocabularyManager_CloseButton {
            get { return ResourceManager.GetString("VocabularyManager_CloseButton", resourceCulture); }
        }
        
        public static string VocabularyManager_Word {
            get { return ResourceManager.GetString("VocabularyManager_Word", resourceCulture); }
        }
        
        public static string VocabularyManager_Pinyin {
            get { return ResourceManager.GetString("VocabularyManager_Pinyin", resourceCulture); }
        }
        
        public static string VocabularyManager_Frequency {
            get { return ResourceManager.GetString("VocabularyManager_Frequency", resourceCulture); }
        }
        
        public static string VocabManager_Status_Ready {
            get { return ResourceManager.GetString("VocabManager_Status_Ready", resourceCulture); }
        }
        
        public static string VocabManager_Stats_Loading {
            get { return ResourceManager.GetString("VocabManager_Stats_Loading", resourceCulture); }
        }
        
        public static string VocabManager_AI_Button {
            get { return ResourceManager.GetString("VocabManager_AI_Button", resourceCulture); }
        }
        
        public static string VocabManager_Learn_Button {
            get { return ResourceManager.GetString("VocabManager_Learn_Button", resourceCulture); }
        }
        
        public static string VocabManager_Toolbar_Add {
            get { return ResourceManager.GetString("VocabManager_Toolbar_Add", resourceCulture); }
        }
        
        public static string VocabManager_Toolbar_Delete {
            get { return ResourceManager.GetString("VocabManager_Toolbar_Delete", resourceCulture); }
        }
        
        public static string VocabManager_Toolbar_Import {
            get { return ResourceManager.GetString("VocabManager_Toolbar_Import", resourceCulture); }
        }
        
        public static string VocabManager_Toolbar_Export {
            get { return ResourceManager.GetString("VocabManager_Toolbar_Export", resourceCulture); }
        }
        
        public static string VocabManager_Toolbar_Refresh {
            get { return ResourceManager.GetString("VocabManager_Toolbar_Refresh", resourceCulture); }
        }
        
        public static string VocabManager_SearchBox_Tooltip {
            get { return ResourceManager.GetString("VocabManager_SearchBox_Tooltip", resourceCulture); }
        }
        
        public static string VocabManager_HistoryTab {
            get { return ResourceManager.GetString("VocabManager_HistoryTab", resourceCulture); }
        }
        
        public static string VocabManager_History_SelectAll {
            get { return ResourceManager.GetString("VocabManager_History_SelectAll", resourceCulture); }
        }
        
        public static string VocabManager_History_SelectNone {
            get { return ResourceManager.GetString("VocabManager_History_SelectNone", resourceCulture); }
        }
        
        public static string VocabManager_History_TrainSelected {
            get { return ResourceManager.GetString("VocabManager_History_TrainSelected", resourceCulture); }
        }
        
        public static string VocabManager_History_AutoTrain {
            get { return ResourceManager.GetString("VocabManager_History_AutoTrain", resourceCulture); }
        }
        
        public static string VocabManager_History_Delete {
            get { return ResourceManager.GetString("VocabManager_History_Delete", resourceCulture); }
        }
        
        public static string VocabManager_History_Filter {
            get { return ResourceManager.GetString("VocabManager_History_Filter", resourceCulture); }
        }
        
        public static string VocabManager_History_FilterToday {
            get { return ResourceManager.GetString("VocabManager_History_FilterToday", resourceCulture); }
        }
        
        public static string VocabManager_History_Filter7Days {
            get { return ResourceManager.GetString("VocabManager_History_Filter7Days", resourceCulture); }
        }
        
        public static string VocabManager_History_Filter30Days {
            get { return ResourceManager.GetString("VocabManager_History_Filter30Days", resourceCulture); }
        }
        
        public static string VocabManager_History_Search_Tooltip {
            get { return ResourceManager.GetString("VocabManager_History_Search_Tooltip", resourceCulture); }
        }
        
        public static string VocabManager_Column_Word {
            get { return ResourceManager.GetString("VocabManager_Column_Word", resourceCulture); }
        }
        
        public static string VocabManager_Column_Pinyin {
            get { return ResourceManager.GetString("VocabManager_Column_Pinyin", resourceCulture); }
        }
        
        public static string VocabManager_Column_Frequency {
            get { return ResourceManager.GetString("VocabManager_Column_Frequency", resourceCulture); }
        }
        
        public static string VocabManager_Column_Weight {
            get { return ResourceManager.GetString("VocabManager_Column_Weight", resourceCulture); }
        }
        
        public static string VocabManager_Column_Category {
            get { return ResourceManager.GetString("VocabManager_Column_Category", resourceCulture); }
        }
        
        public static string VocabManager_Column_Source {
            get { return ResourceManager.GetString("VocabManager_Column_Source", resourceCulture); }
        }
        
        public static string VocabManager_Column_Contexts {
            get { return ResourceManager.GetString("VocabManager_Column_Contexts", resourceCulture); }
        }
        
        public static string VocabManager_Column_LastUsed {
            get { return ResourceManager.GetString("VocabManager_Column_LastUsed", resourceCulture); }
        }
        
        public static string VocabCategory_General {
            get { return ResourceManager.GetString("VocabCategory_General", resourceCulture); }
        }
        
        public static string VocabCategory_Medical {
            get { return ResourceManager.GetString("VocabCategory_Medical", resourceCulture); }
        }
        
        public static string VocabCategory_Legal {
            get { return ResourceManager.GetString("VocabCategory_Legal", resourceCulture); }
        }
        
        public static string VocabCategory_Tech {
            get { return ResourceManager.GetString("VocabCategory_Tech", resourceCulture); }
        }
        
        public static string VocabCategory_Business {
            get { return ResourceManager.GetString("VocabCategory_Business", resourceCulture); }
        }
        
        public static string VocabCategory_Academic {
            get { return ResourceManager.GetString("VocabCategory_Academic", resourceCulture); }
        }
        
        public static string VocabCategory_Programming {
            get { return ResourceManager.GetString("VocabCategory_Programming", resourceCulture); }
        }
        
        public static string VocabSource_Manual {
            get { return ResourceManager.GetString("VocabSource_Manual", resourceCulture); }
        }
        
        public static string VocabSource_AIGenerated {
            get { return ResourceManager.GetString("VocabSource_AIGenerated", resourceCulture); }
        }
        
        public static string VocabSource_AutoLearned {
            get { return ResourceManager.GetString("VocabSource_AutoLearned", resourceCulture); }
        }
        
        public static string VocabSource_Input {
            get { return ResourceManager.GetString("VocabSource_Input", resourceCulture); }
        }
        
        public static string VocabSource_Correction {
            get { return ResourceManager.GetString("VocabSource_Correction", resourceCulture); }
        }
        #endregion
        
        #region Vocabulary Page
        public static string VocabPage_BackButton {
            get { return ResourceManager.GetString("VocabPage_BackButton", resourceCulture); }
        }
        
        public static string VocabPage_Title {
            get { return ResourceManager.GetString("VocabPage_Title", resourceCulture); }
        }
        
        public static string VocabPage_StatsText {
            get { return ResourceManager.GetString("VocabPage_StatsText", resourceCulture); }
        }
        
        public static string VocabPage_AIButton {
            get { return ResourceManager.GetString("VocabPage_AIButton", resourceCulture); }
        }
        
        public static string VocabPage_LearnButton {
            get { return ResourceManager.GetString("VocabPage_LearnButton", resourceCulture); }
        }
        
        public static string VocabPage_TabVocabulary {
            get { return ResourceManager.GetString("VocabPage_TabVocabulary", resourceCulture); }
        }
        
        public static string VocabPage_TabHistory {
            get { return ResourceManager.GetString("VocabPage_TabHistory", resourceCulture); }
        }
        
        public static string VocabPage_AddButton {
            get { return ResourceManager.GetString("VocabPage_AddButton", resourceCulture); }
        }
        
        public static string VocabPage_DeleteButton {
            get { return ResourceManager.GetString("VocabPage_DeleteButton", resourceCulture); }
        }
        
        public static string VocabPage_ImportButton {
            get { return ResourceManager.GetString("VocabPage_ImportButton", resourceCulture); }
        }
        
        public static string VocabPage_ExportButton {
            get { return ResourceManager.GetString("VocabPage_ExportButton", resourceCulture); }
        }
        
        public static string VocabPage_RefreshButton {
            get { return ResourceManager.GetString("VocabPage_RefreshButton", resourceCulture); }
        }
        
        public static string VocabPage_SearchBox {
            get { return ResourceManager.GetString("VocabPage_SearchBox", resourceCulture); }
        }
        
        public static string VocabPage_SelectAll {
            get { return ResourceManager.GetString("VocabPage_SelectAll", resourceCulture); }
        }
        
        public static string VocabPage_SelectNone {
            get { return ResourceManager.GetString("VocabPage_SelectNone", resourceCulture); }
        }
        
        public static string VocabPage_TrainSelected {
            get { return ResourceManager.GetString("VocabPage_TrainSelected", resourceCulture); }
        }
        
        public static string VocabPage_AutoTrain {
            get { return ResourceManager.GetString("VocabPage_AutoTrain", resourceCulture); }
        }
        
        public static string VocabPage_FilterAll {
            get { return ResourceManager.GetString("VocabPage_FilterAll", resourceCulture); }
        }
        
        public static string VocabPage_FilterToday {
            get { return ResourceManager.GetString("VocabPage_FilterToday", resourceCulture); }
        }
        
        public static string VocabPage_Filter7Days {
            get { return ResourceManager.GetString("VocabPage_Filter7Days", resourceCulture); }
        }
        
        public static string VocabPage_Filter30Days {
            get { return ResourceManager.GetString("VocabPage_Filter30Days", resourceCulture); }
        }
        
        public static string VocabPage_StatusReady {
            get { return ResourceManager.GetString("VocabPage_StatusReady", resourceCulture); }
        }
        
        public static string VocabPage_QuickAddTitle {
            get { return ResourceManager.GetString("VocabPage_QuickAddTitle", resourceCulture); }
        }
        
        public static string VocabPage_QuickAddHint {
            get { return ResourceManager.GetString("VocabPage_QuickAddHint", resourceCulture); }
        }
        
        public static string VocabPage_QuickAddButton {
            get { return ResourceManager.GetString("VocabPage_QuickAddButton", resourceCulture); }
        }
        
        public static string VocabPage_QuickAddCategory {
            get { return ResourceManager.GetString("VocabPage_QuickAddCategory", resourceCulture); }
        }
        
        public static string VocabPage_ExportSuccess {
            get { return ResourceManager.GetString("VocabPage_ExportSuccess", resourceCulture); }
        }
        
        public static string VocabPage_ExportFailed {
            get { return ResourceManager.GetString("VocabPage_ExportFailed", resourceCulture); }
        }
        
        public static string VocabPage_ExportOpenFolder {
            get { return ResourceManager.GetString("VocabPage_ExportOpenFolder", resourceCulture); }
        }
        
        public static string VocabPage_DeleteConfirm {
            get { return ResourceManager.GetString("VocabPage_DeleteConfirm", resourceCulture); }
        }
        
        public static string VocabPage_DeleteTitle {
            get { return ResourceManager.GetString("VocabPage_DeleteTitle", resourceCulture); }
        }
        
        public static string VocabPage_SelectWordFirst {
            get { return ResourceManager.GetString("VocabPage_SelectWordFirst", resourceCulture); }
        }
        
        public static string VocabPage_AddSuccess {
            get { return ResourceManager.GetString("VocabPage_AddSuccess", resourceCulture); }
        }
        
        public static string VocabPage_LoadingVocab {
            get { return ResourceManager.GetString("VocabPage_LoadingVocab", resourceCulture); }
        }
        
        public static string VocabPage_LoadingHistory {
            get { return ResourceManager.GetString("VocabPage_LoadingHistory", resourceCulture); }
        }
        
        public static string VocabPage_LearnConfirm {
            get { return ResourceManager.GetString("VocabPage_LearnConfirm", resourceCulture); }
        }
        
        public static string VocabPage_LearnTitle {
            get { return ResourceManager.GetString("VocabPage_LearnTitle", resourceCulture); }
        }
        
        public static string VocabPage_Learning {
            get { return ResourceManager.GetString("VocabPage_Learning", resourceCulture); }
        }
        
        public static string VocabPage_LearnComplete {
            get { return ResourceManager.GetString("VocabPage_LearnComplete", resourceCulture); }
        }
        
        public static string VocabPage_LearnResult {
            get { return ResourceManager.GetString("VocabPage_LearnResult", resourceCulture); }
        }
        
        public static string VocabPage_AIConfirm {
            get { return ResourceManager.GetString("VocabPage_AIConfirm", resourceCulture); }
        }
        
        public static string VocabPage_AITitle {
            get { return ResourceManager.GetString("VocabPage_AITitle", resourceCulture); }
        }
        
        public static string VocabPage_AIAnalyzing {
            get { return ResourceManager.GetString("VocabPage_AIAnalyzing", resourceCulture); }
        }
        
        public static string VocabPage_AIComplete {
            get { return ResourceManager.GetString("VocabPage_AIComplete", resourceCulture); }
        }
        
        public static string VocabPage_AIResult {
            get { return ResourceManager.GetString("VocabPage_AIResult", resourceCulture); }
        }
        
        public static string VocabPage_TrainProgress {
            get { return ResourceManager.GetString("VocabPage_TrainProgress", resourceCulture); }
        }
        
        public static string VocabPage_SelectHistoryFirst {
            get { return ResourceManager.GetString("VocabPage_SelectHistoryFirst", resourceCulture); }
        }
        
        public static string VocabPage_TrainResult {
            get { return ResourceManager.GetString("VocabPage_TrainResult", resourceCulture); }
        }
        
        public static string VocabPage_AutoTrainConfirm {
            get { return ResourceManager.GetString("VocabPage_AutoTrainConfirm", resourceCulture); }
        }
        
        public static string VocabPage_AutoTrainTitle {
            get { return ResourceManager.GetString("VocabPage_AutoTrainTitle", resourceCulture); }
        }
        
        public static string VocabPage_AutoTraining {
            get { return ResourceManager.GetString("VocabPage_AutoTraining", resourceCulture); }
        }
        
        public static string VocabPage_AutoTrainComplete {
            get { return ResourceManager.GetString("VocabPage_AutoTrainComplete", resourceCulture); }
        }
        
        public static string VocabPage_DeleteHistoryConfirm {
            get { return ResourceManager.GetString("VocabPage_DeleteHistoryConfirm", resourceCulture); }
        }
        
        public static string VocabPage_SelectHistoryToDelete {
            get { return ResourceManager.GetString("VocabPage_SelectHistoryToDelete", resourceCulture); }
        }
        
        public static string VocabPage_DeleteSuccess {
            get { return ResourceManager.GetString("VocabPage_DeleteSuccess", resourceCulture); }
        }
        
        public static string VocabPage_Filtering {
            get { return ResourceManager.GetString("VocabPage_Filtering", resourceCulture); }
        }
        
        public static string VocabPage_FoundRecords {
            get { return ResourceManager.GetString("VocabPage_FoundRecords", resourceCulture); }
        }
        
        public static string VocabPage_TotalRecords {
            get { return ResourceManager.GetString("VocabPage_TotalRecords", resourceCulture); }
        }
        
        public static string VocabPage_ServiceNotInit {
            get { return ResourceManager.GetString("VocabPage_ServiceNotInit", resourceCulture); }
        }
        
        public static string VocabPage_LoadFailed {
            get { return ResourceManager.GetString("VocabPage_LoadFailed", resourceCulture); }
        }
        
        public static string VocabPage_AddFailed {
            get { return ResourceManager.GetString("VocabPage_AddFailed", resourceCulture); }
        }
        
        public static string VocabPage_DeleteFailed {
            get { return ResourceManager.GetString("VocabPage_DeleteFailed", resourceCulture); }
        }
        
        public static string VocabPage_ImportFailed {
            get { return ResourceManager.GetString("VocabPage_ImportFailed", resourceCulture); }
        }
        
        public static string VocabPage_ImportSuccess {
            get { return ResourceManager.GetString("VocabPage_ImportSuccess", resourceCulture); }
        }
        
        public static string VocabPage_Importing {
            get { return ResourceManager.GetString("VocabPage_Importing", resourceCulture); }
        }
        
        public static string VocabPage_Exporting {
            get { return ResourceManager.GetString("VocabPage_Exporting", resourceCulture); }
        }
        #endregion
        
        #region Messages
        public static string Message_SaveSuccess {
            get { return ResourceManager.GetString("Message_SaveSuccess", resourceCulture); }
        }
        
        public static string Message_SaveFailed {
            get { return ResourceManager.GetString("Message_SaveFailed", resourceCulture); }
        }
        
        public static string Message_DownloadComplete {
            get { return ResourceManager.GetString("Message_DownloadComplete", resourceCulture); }
        }
        
        public static string Message_DownloadFailed {
            get { return ResourceManager.GetString("Message_DownloadFailed", resourceCulture); }
        }
        
        public static string Message_ConfirmDelete {
            get { return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture); }
        }
        
        public static string Message_RestartRequired {
            get { return ResourceManager.GetString("Message_RestartRequired", resourceCulture); }
        }
        #endregion
        
        #region System Tray
        public static string Tray_ShowWindow {
            get { return ResourceManager.GetString("Tray_ShowWindow", resourceCulture); }
        }
        
        public static string Tray_Settings {
            get { return ResourceManager.GetString("Tray_Settings", resourceCulture); }
        }
        
        public static string Tray_VocabularyManager {
            get { return ResourceManager.GetString("Tray_VocabularyManager", resourceCulture); }
        }
        
        public static string Tray_History {
            get { return ResourceManager.GetString("Tray_History", resourceCulture); }
        }
        
        public static string Tray_StartOnBoot {
            get { return ResourceManager.GetString("Tray_StartOnBoot", resourceCulture); }
        }
        
        public static string Tray_Exit {
            get { return ResourceManager.GetString("Tray_Exit", resourceCulture); }
        }
        #endregion
        
        #region Update Dialog
        public static string UpdateDialog_Title {
            get { return ResourceManager.GetString("UpdateDialog_Title", resourceCulture); }
        }
        
        public static string UpdateDialog_ReleaseDate {
            get { return ResourceManager.GetString("UpdateDialog_ReleaseDate", resourceCulture); }
        }
        
        public static string UpdateDialog_SkipButton {
            get { return ResourceManager.GetString("UpdateDialog_SkipButton", resourceCulture); }
        }
        
        public static string UpdateDialog_LaterButton {
            get { return ResourceManager.GetString("UpdateDialog_LaterButton", resourceCulture); }
        }
        
        public static string UpdateDialog_UpdateButton {
            get { return ResourceManager.GetString("UpdateDialog_UpdateButton", resourceCulture); }
        }
        
        public static string UpdateDialog_SkipDisabledTooltip {
            get { return ResourceManager.GetString("UpdateDialog_SkipDisabledTooltip", resourceCulture); }
        }
        
        public static string UpdateDialog_NoChanges {
            get { return ResourceManager.GetString("UpdateDialog_NoChanges", resourceCulture); }
        }
        
        public static string UpdateDialog_Verifying {
            get { return ResourceManager.GetString("UpdateDialog_Verifying", resourceCulture); }
        }
        
        public static string UpdateDialog_VerificationFailed {
            get { return ResourceManager.GetString("UpdateDialog_VerificationFailed", resourceCulture); }
        }
        
        public static string UpdateDialog_Error {
            get { return ResourceManager.GetString("UpdateDialog_Error", resourceCulture); }
        }
        
        public static string UpdateDialog_ReadyToInstall {
            get { return ResourceManager.GetString("UpdateDialog_ReadyToInstall", resourceCulture); }
        }
        
        public static string UpdateDialog_Install {
            get { return ResourceManager.GetString("UpdateDialog_Install", resourceCulture); }
        }
        
        public static string UpdateDialog_Installing {
            get { return ResourceManager.GetString("UpdateDialog_Installing", resourceCulture); }
        }
        
        public static string UpdateDialog_InstallSuccess {
            get { return ResourceManager.GetString("UpdateDialog_InstallSuccess", resourceCulture); }
        }
        
        public static string UpdateDialog_Success {
            get { return ResourceManager.GetString("UpdateDialog_Success", resourceCulture); }
        }
        
        public static string UpdateDialog_InstallFailed {
            get { return ResourceManager.GetString("UpdateDialog_InstallFailed", resourceCulture); }
        }
        
        public static string UpdateDialog_Cancelled {
            get { return ResourceManager.GetString("UpdateDialog_Cancelled", resourceCulture); }
        }
        
        public static string UpdateDialog_DownloadFailed {
            get { return ResourceManager.GetString("UpdateDialog_DownloadFailed", resourceCulture); }
        }
        
        public static string UpdateDialog_RemainingTime {
            get { return ResourceManager.GetString("UpdateDialog_RemainingTime", resourceCulture); }
        }
        
        public static string UpdateDialog_Seconds {
            get { return ResourceManager.GetString("UpdateDialog_Seconds", resourceCulture); }
        }
        #endregion
    }
}
